# Generated by Django 5.2.5 on 2025-08-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_consultationreport_user_delete_consultation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
